alter table articlecomment drop foreign key FK6mxverhrr5rsel5msd57e9as0;
alter table articlecomment drop foreign key FK2y4u22wnwi60je4wpokuprt0l;
alter table opinionbase_opinionbase drop foreign key FK6379jcqn5k2n64fa131c6p7pr;
alter table opinionbase_opinionbase drop foreign key FK8w9a21gdq0lgu54qfebqyl79n;
alter table opinionstatutecitation drop foreign key FKeexbenv8629lcogonxq8gh3li;
alter table opinionstatutecitation drop foreign key FKrox3hujmktp9v01boc27ab4f4;
alter table opinionsummary drop foreign key FKnt66scy9e8klmd9h6r8dsn7ov;
alter table slipopinion drop foreign key FKj82kph5p1h9a2fny9nyrn2hqv;
alter table user_role drop foreign key FKeog8p06nu33ihk13roqnrp1y6;
alter table user_role drop foreign key FK859n2jvi8ivhui0rl0esws6o;
drop table if exists article;
drop table if exists articlecomment;
drop table if exists opinionbase;
drop table if exists opinionbase_opinionbase;
drop table if exists opinionstatutecitation;
drop table if exists opinionsummary;
drop table if exists role;
drop table if exists slipopinion;
drop table if exists statutecitation;
drop table if exists user;
drop table if exists user_role;
create table article (id bigint not null auto_increment, contents varchar(255), date datetime, title varchar(255), primary key (id)) ENGINE=InnoDB;
create table articlecomment (id bigint not null auto_increment, comment varchar(255), importance integer not null, article_id bigint, user_id bigint, primary key (id)) ENGINE=InnoDB;
create table opinionbase (page bigint not null, volume integer not null, vset integer not null, countreferringopinions integer not null, court TEXT, opiniondate date, title TEXT, primary key (page, volume, vset)) ENGINE=InnoDB;
create table opinionbase_opinionbase (referringopinions_page bigint not null, referringopinions_volume integer not null, referringopinions_vset integer not null, opinioncitations_page bigint not null, opinioncitations_volume integer not null, opinioncitations_vset integer not null, primary key (referringopinions_page, referringopinions_volume, referringopinions_vset, opinioncitations_page, opinioncitations_volume, opinioncitations_vset)) ENGINE=InnoDB;
create table opinionstatutecitation (countreferences integer not null, opinionbase_page bigint not null, opinionbase_volume integer not null, opinionbase_vset integer not null, statutecitation_sectionnumber char(32) not null, statutecitation_title char(3) not null, primary key (opinionbase_page, opinionbase_volume, opinionbase_vset, statutecitation_sectionnumber, statutecitation_title)) ENGINE=InnoDB;
create table opinionsummary (page bigint not null, volume integer not null, vset integer not null, primary key (page, volume, vset)) ENGINE=InnoDB;
create table role (id bigint not null auto_increment, role varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table slipopinion (disposition TEXT, fileextension TEXT, filename TEXT, summary TEXT, page bigint not null, volume integer not null, vset integer not null, primary key (page, volume, vset)) ENGINE=InnoDB;
create table statutecitation (sectionnumber char(32) not null, title char(3) not null, designated bit not null, primary key (sectionnumber, title)) ENGINE=InnoDB;
create table user (id bigint not null auto_increment, createdate datetime, email varchar(255), emailupdates bit not null, firstname varchar(255), lastname varchar(255), locale varchar(255), optout bit not null, optoutkey varchar(255), password varchar(255), titles tinyblob, updatedate datetime, verified bit not null, verifycount integer not null, verifyerrors integer not null, verifykey varchar(255), welcomeerrors integer not null, welcomed bit not null, primary key (id)) ENGINE=InnoDB;
create table user_role (user_id bigint not null, roles_id bigint not null) ENGINE=InnoDB;
alter table role add constraint UK_bjxn5ii7v7ygwx39et0wawu0q unique (role);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table articlecomment add constraint FK6mxverhrr5rsel5msd57e9as0 foreign key (article_id) references article (id);
alter table articlecomment add constraint FK2y4u22wnwi60je4wpokuprt0l foreign key (user_id) references user (id);
alter table opinionbase_opinionbase add constraint FK6379jcqn5k2n64fa131c6p7pr foreign key (opinioncitations_page, opinioncitations_volume, opinioncitations_vset) references opinionbase (page, volume, vset);
alter table opinionbase_opinionbase add constraint FK8w9a21gdq0lgu54qfebqyl79n foreign key (referringopinions_page, referringopinions_volume, referringopinions_vset) references opinionbase (page, volume, vset);
alter table opinionstatutecitation add constraint FKeexbenv8629lcogonxq8gh3li foreign key (opinionbase_page, opinionbase_volume, opinionbase_vset) references opinionbase (page, volume, vset);
alter table opinionstatutecitation add constraint FKrox3hujmktp9v01boc27ab4f4 foreign key (statutecitation_sectionnumber, statutecitation_title) references statutecitation (sectionnumber, title);
alter table opinionsummary add constraint FKnt66scy9e8klmd9h6r8dsn7ov foreign key (page, volume, vset) references opinionbase (page, volume, vset);
alter table slipopinion add constraint FKj82kph5p1h9a2fny9nyrn2hqv foreign key (page, volume, vset) references opinionbase (page, volume, vset);
alter table user_role add constraint FKeog8p06nu33ihk13roqnrp1y6 foreign key (roles_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
