alter table opinionbase_opinionbase drop foreign key FK9sll5n03kie5mj1yqjxwlyeji;
alter table opinionbase_opinionbase drop foreign key FK279m8be1k5wqm8gh65623xo7a;
alter table opinionstatutecitation drop foreign key FKbc7gkn9yregdcsntvsr679ywc;
alter table opinionstatutecitation drop foreign key FKrox3hujmktp9v01boc27ab4f4;
alter table slipopinion drop foreign key FKk07cockbefpusdjmqh0soxlnm;
alter table user_role drop foreign key FKeog8p06nu33ihk13roqnrp1y6;
alter table user_role drop foreign key FK859n2jvi8ivhui0rl0esws6o;
drop table if exists opinionbase;
drop table if exists opinionbase_opinionbase;
drop table if exists opinionstatutecitation;
drop table if exists role;
drop table if exists slipopinion;
drop table if exists statutecitation;
drop table if exists user;
drop table if exists user_role;
create table opinionbase (opinionkey bigint not null, countreferringopinions integer not null, court TEXT, opiniondate date, title TEXT, primary key (opinionkey)) ENGINE=InnoDB;
create table opinionbase_opinionbase (referringopinions_opinionkey bigint not null, opinioncitations_opinionkey bigint not null, primary key (referringopinions_opinionkey, opinioncitations_opinionkey)) ENGINE=InnoDB;
create table opinionstatutecitation (countreferences integer not null, opinionbase_opinionkey bigint not null, statutecitation_sectionnumber char(32) not null, statutecitation_title char(3) not null, primary key (opinionbase_opinionkey, statutecitation_sectionnumber, statutecitation_title)) ENGINE=InnoDB;
create table role (id bigint not null auto_increment, role varchar(255) not null, primary key (id)) ENGINE=InnoDB;
create table slipopinion (disposition TEXT, fileextension TEXT, filename TEXT, summary TEXT, opinionkey bigint not null, primary key (opinionkey)) ENGINE=InnoDB;
create table statutecitation (sectionnumber char(32) not null, title char(3) not null, designated bit not null, primary key (sectionnumber, title)) ENGINE=InnoDB;
create table user (id bigint not null auto_increment, createdate datetime, email varchar(255), emailupdates bit not null, firstname varchar(255), lastname varchar(255), locale varchar(255), optout bit not null, optoutkey varchar(255), password varchar(255), titles tinyblob, updatedate datetime, verified bit not null, verifycount integer not null, verifyerrors integer not null, verifykey varchar(255), welcomeerrors integer not null, welcomed bit not null, primary key (id)) ENGINE=InnoDB;
create table user_role (user_id bigint not null, roles_id bigint not null) ENGINE=InnoDB;
alter table role add constraint UK_bjxn5ii7v7ygwx39et0wawu0q unique (role);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table opinionbase_opinionbase add constraint FK9sll5n03kie5mj1yqjxwlyeji foreign key (opinioncitations_opinionkey) references opinionbase (opinionkey);
alter table opinionbase_opinionbase add constraint FK279m8be1k5wqm8gh65623xo7a foreign key (referringopinions_opinionkey) references opinionbase (opinionkey);
alter table opinionstatutecitation add constraint FKbc7gkn9yregdcsntvsr679ywc foreign key (opinionbase_opinionkey) references opinionbase (opinionkey);
alter table opinionstatutecitation add constraint FKrox3hujmktp9v01boc27ab4f4 foreign key (statutecitation_sectionnumber, statutecitation_title) references statutecitation (sectionnumber, title);
alter table slipopinion add constraint FKk07cockbefpusdjmqh0soxlnm foreign key (opinionkey) references opinionbase (opinionkey);
alter table user_role add constraint FKeog8p06nu33ihk13roqnrp1y6 foreign key (roles_id) references role (id);
alter table user_role add constraint FK859n2jvi8ivhui0rl0esws6o foreign key (user_id) references user (id);
