package statutews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-11T12:31:25.603-07:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "StatuteWSService", 
                  wsdlLocation = "http://localhost:8080/statutews-endpoint/StatuteWS?wsdl",
                  targetNamespace = "http://statutews/") 
public class StatuteWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://statutews/", "StatuteWSService");
    public final static QName StatuteWSPort = new QName("http://statutews/", "StatuteWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/statutews-endpoint/StatuteWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StatuteWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/statutews-endpoint/StatuteWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StatuteWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StatuteWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatuteWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StatuteWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StatuteWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StatuteWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StatuteWS
     */
    @WebEndpoint(name = "StatuteWSPort")
    public StatuteWS getStatuteWSPort() {
        return super.getPort(StatuteWSPort, StatuteWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatuteWS
     */
    @WebEndpoint(name = "StatuteWSPort")
    public StatuteWS getStatuteWSPort(WebServiceFeature... features) {
        return super.getPort(StatuteWSPort, StatuteWS.class, features);
    }

}
