package statutews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-17T19:27:45.823-07:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://statutews/", name = "StatuteWS")
@XmlSeeAlso({ObjectFactory.class, statutes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface StatuteWS {

    @WebMethod
    @WebResult(name = "responseArray", targetNamespace = "http://statutews/", partName = "responseArray")
    public ResponseArray echo(
        @WebParam(partName = "arg0", name = "arg0")
        StatuteKeyArray arg0
    );
}
