package statutews;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2016-08-13T14:55:01.951-07:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://statutews/", name = "StatuteWS")
@XmlSeeAlso({ObjectFactory.class, statutes.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface StatuteWS {

    @WebMethod
    @WebResult(name = "return", targetNamespace = "http://statutews/", partName = "return")
    public statutes.StatutesBaseClassArray echo(
        @WebParam(partName = "arg0", name = "arg0")
        StatuteKeyArray arg0
    );
}
